version: "3.9"  # optional since v1.27.0

services:

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    volumes:
      - ./requirements/wordpress/html:/var/www/html/
    networks:
      - wordpress
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "8443:443"
      - "8080:80"
    volumes:
      - ./requirements/wordpress/html:/var/www/html/
    depends_on:
      - wordpress
    networks:
      - wordpress
    restart: always

networks:
  wordpress:
    name: wp-wordpress
    driver: bridge