version: "3.9"

services:
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    environment:
      - DOMAIN_NAME
    ports:
      - 9000:9000
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - wordpress
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    environment:
      - DOMAIN_NAME
    ports:
      - "8443:443"
      - "8080:80"
    volumes:
      - wordpress:/var/www/html/wordpress
    depends_on:
      - wordpress
    networks:
      - wordpress
    restart: always
networks:
  wordpress:
    name: wp-wordpress
    driver: bridge

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "$HOME/data/wordpress"
