version: "3.9"

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      args:
        - MYSQL_ROOT_PASSWORD
        - MYSQL_USER
        - MYSQL_PASSWORD
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
    ports:
      - 3360:3306
    volumes:
      - database:/var/lib/mysql
    networks:
      - wordpress

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    environment:
      - DB_HOST
      - DB_NAME
      - MYSQL_USER
      - MYSQL_PASSWORD
      - WP_DOMAIN
      - WP_SCHEME
      - WP_PORT
      - WP_TITLE
      - WP_ADMIN
      - WP_ADMIN_PASSWORD
      - WP_ADMIN_EMAIL
      - WP_USER
      - WP_USER_EMAIL
      - WP_USER_PASSWORD
    ports:
      - 9000:9000
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - wordpress
    depends_on:
      - mariadb
      - redis
    restart: always

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    environment:
      - WP_DOMAIN
    ports:
      - 8443:443
      - 8080:80
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - wordpress
    depends_on:
      - wordpress
    restart: always

  redis:
    container_name: redis
    build:
      context: ./requirements/redis
    ports:
      - 6379:6379
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - wordpress
    restart: always

  ftpserver:
    container_name: ftpserver
    build:
      context: ./requirements/ftpserver
    environment:
      - FT_USER
      - FT_PASS
    ports:
      - 21:21
      - 20:20
      - 40000-40009:40000-40009
    networks:
      - wordpress
    restart: always
    volumes:
      - /data:/home/$FT_USER

  prometheus:
    container_name: prometheus
    build:
      context: ./requirements/prometheus
    ports:
      - 9090:9090
    volumes:
      - $HOME/data/prometheus:/data/prometheus
    networks:
      - wordpress
    restart: always

networks:
  wordpress:
    name: wp-wordpress
    driver: bridge
  mariadb:
    name: db-mariadb
    driver: bridge

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: "bind"
      device: $HOME/data/wordpress
  database:
    driver: local
    driver_opts:
      type: none
      o: "bind"
      device: $HOME/data/database
